export const PARAS: { number: number; name: string; arabic: string }[] = [
  { number: 1, name: "Alif Lam Meem", arabic: "الٓمّٓ" },
  { number: 2, name: "Sayaqul", arabic: "سَيَقُولُ" },
  { number: 3, name: "Tilkal Rusul", arabic: "تِلْكَ الرُّسُلُ" },
  { number: 4, name: "Lan Tanaloo", arabic: "لَنْ تَنَالُوا" },
  { number: 5, name: "Wal Mohsanat", arabic: "وَالْمُحْصَنَاتُ" },
  { number: 6, name: "La Yuhibbullah", arabic: "لَا يُحِبُّ اللهُ" },
  { number: 7, name: "Wa Iza Sami'u", arabic: "وَإِذَا سَمِعُوا" },
  { number: 8, name: "Wa Lau Annana", arabic: "وَلَوْ أَنَّنَا" },
  { number: 9, name: "Qalal Mala'u", arabic: "قَالَ الْمَلَأُ" },
  { number: 10, name: "Wa A'lamu", arabic: "وَاعْلَمُوا" },
  { number: 11, name: "Ya'tazeroon", arabic: "يَعْتَذِرُونَ" },
  { number: 12, name: "Wa Ma Min Dabbah", arabic: "وَمَا مِنْ دَابَّةٍ" },
  { number: 13, name: "Wa Ma Ubarri'u", arabic: "وَمَا أُبَرِّئُ" },
  { number: 14, name: "Rubama", arabic: "رُبَمَا" },
  { number: 15, name: "Subhanalladhi", arabic: "سُبْحَانَ الَّذِي" },
  { number: 16, name: "Qal Alam", arabic: "قَالَ أَلَمْ" },
  { number: 17, name: "Iqtaraba", arabic: "اقْتَرَبَ" },
  { number: 18, name: "Qad Aflaha", arabic: "قَدْ أَفْلَحَ" },
  { number: 19, name: "Wa Qalalladhina", arabic: "وَقَالَ الَّذِينَ" },
  { number: 20, name: "Amman Khalaqa", arabic: "أَمَّنْ خَلَقَ" },
  { number: 21, name: "Utlu Ma Oohiya", arabic: "اتْلُ مَا أُوحِيَ" },
  { number: 22, name: "Wa Man Yaqnut", arabic: "وَمَنْ يَقْنُتْ" },
  { number: 23, name: "Wa Mali", arabic: "وَمَا لِيَ" },
  { number: 24, name: "Faman Azlam", arabic: "فَمَنْ أَظْلَمُ" },
  { number: 25, name: "Ilayhi Yuraddu", arabic: "إِلَيْهِ يُرَدُّ" },
  { number: 26, name: "Ha Meem", arabic: "حٰمٓ" },
  { number: 27, name: "Qala Fama Khatbukum", arabic: "قَالَ فَمَا خَطْبُكُمْ" },
  { number: 28, name: "Qad Sami Allah", arabic: "قَدْ سَمِعَ اللهُ" },
  { number: 29, name: "Tabarakalladhi", arabic: "تَبَارَكَ الَّذِي" },
  { number: 30, name: "Amma Yatasa'aloon", arabic: "عَمَّ يَتَسَاءَلُونَ" },
];
