/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as MasnoonDuainRouteImport } from './routes/masnoon-duain'
import { Route as ParasRouteImport } from './routes/paras'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SurahsRouteImport } from './routes/surahs'
import { Route as MasnoonDuainIdRouteImport } from './routes/masnoon-duain.$id'
import { Route as ParaIdRouteImport } from './routes/para.$id'
import { Route as SurahIdRouteImport } from './routes/surah.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const MasnoonDuainRoute = MasnoonDuainRouteImport.update({
  id: '/masnoon-duain',
  path: '/masnoon-duain',
  getParentRoute: () => rootRouteImport,
} as any)
const ParasRoute = ParasRouteImport.update({
  id: '/paras',
  path: '/paras',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahsRoute = SurahsRouteImport.update({
  id: '/surahs',
  path: '/surahs',
  getParentRoute: () => rootRouteImport,
} as any)
const MasnoonDuainIdRoute = MasnoonDuainIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MasnoonDuainRoute,
} as any)
const ParaIdRoute = ParaIdRouteImport.update({
  id: '/para/$id',
  path: '/para/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahIdRoute = SurahIdRouteImport.update({
  id: '/surah/$id',
  path: '/surah/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/intro': typeof IntroRoute
  '/masnoon-duain': typeof MasnoonDuainRouteWithChildren
  '/paras': typeof ParasRoute
  '/settings': typeof SettingsRoute
  '/surahs': typeof SurahsRoute
  '/masnoon-duain/$id': typeof MasnoonDuainIdRoute
  '/para/$id': typeof ParaIdRoute
  '/surah/$id': typeof SurahIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/intro': typeof IntroRoute
  '/masnoon-duain': typeof MasnoonDuainRouteWithChildren
  '/paras': typeof ParasRoute
  '/settings': typeof SettingsRoute
  '/surahs': typeof SurahsRoute
  '/masnoon-duain/$id': typeof MasnoonDuainIdRoute
  '/para/$id': typeof ParaIdRoute
  '/surah/$id': typeof SurahIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/intro': typeof IntroRoute
  '/masnoon-duain': typeof MasnoonDuainRouteWithChildren
  '/paras': typeof ParasRoute
  '/settings': typeof SettingsRoute
  '/surahs': typeof SurahsRoute
  '/masnoon-duain/$id': typeof MasnoonDuainIdRoute
  '/para/$id': typeof ParaIdRoute
  '/surah/$id': typeof SurahIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete'
    | '/intro'
    | '/masnoon-duain'
    | '/paras'
    | '/settings'
    | '/surahs'
    | '/masnoon-duain/$id'
    | '/para/$id'
    | '/surah/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete'
    | '/intro'
    | '/masnoon-duain'
    | '/paras'
    | '/settings'
    | '/surahs'
    | '/masnoon-duain/$id'
    | '/para/$id'
    | '/surah/$id'
  id:
    | '__root__'
    | '/'
    | '/complete'
    | '/intro'
    | '/masnoon-duain'
    | '/paras'
    | '/settings'
    | '/surahs'
    | '/masnoon-duain/$id'
    | '/para/$id'
    | '/surah/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompleteRoute: typeof CompleteRoute
  IntroRoute: typeof IntroRoute
  MasnoonDuainRoute: typeof MasnoonDuainRouteWithChildren
  ParasRoute: typeof ParasRoute
  SettingsRoute: typeof SettingsRoute
  SurahsRoute: typeof SurahsRoute
  ParaIdRoute: typeof ParaIdRoute
  SurahIdRoute: typeof SurahIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masnoon-duain': {
      id: '/masnoon-duain'
      path: '/masnoon-duain'
      fullPath: '/masnoon-duain'
      preLoaderRoute: typeof MasnoonDuainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paras': {
      id: '/paras'
      path: '/paras'
      fullPath: '/paras'
      preLoaderRoute: typeof ParasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surahs': {
      id: '/surahs'
      path: '/surahs'
      fullPath: '/surahs'
      preLoaderRoute: typeof SurahsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masnoon-duain/$id': {
      id: '/masnoon-duain/$id'
      path: '/$id'
      fullPath: '/masnoon-duain/$id'
      preLoaderRoute: typeof MasnoonDuainIdRouteImport
      parentRoute: typeof MasnoonDuainRoute
    }
    '/para/$id': {
      id: '/para/$id'
      path: '/para/$id'
      fullPath: '/para/$id'
      preLoaderRoute: typeof ParaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surah/$id': {
      id: '/surah/$id'
      path: '/surah/$id'
      fullPath: '/surah/$id'
      preLoaderRoute: typeof SurahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MasnoonDuainRouteChildren {
  MasnoonDuainIdRoute: typeof MasnoonDuainIdRoute
}

const MasnoonDuainRouteChildren: MasnoonDuainRouteChildren = {
  MasnoonDuainIdRoute: MasnoonDuainIdRoute,
}

const MasnoonDuainRouteWithChildren = MasnoonDuainRoute._addFileChildren(
  MasnoonDuainRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompleteRoute: CompleteRoute,
  IntroRoute: IntroRoute,
  MasnoonDuainRoute: MasnoonDuainRouteWithChildren,
  ParasRoute: ParasRoute,
  SettingsRoute: SettingsRoute,
  SurahsRoute: SurahsRoute,
  ParaIdRoute: ParaIdRoute,
  SurahIdRoute: SurahIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
