/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as ParasRouteImport } from './routes/paras'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ParaIdRouteImport } from './routes/para.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const ParasRoute = ParasRouteImport.update({
  id: '/paras',
  path: '/paras',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaIdRoute = ParaIdRouteImport.update({
  id: '/para/$id',
  path: '/para/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/intro': typeof IntroRoute
  '/paras': typeof ParasRoute
  '/settings': typeof SettingsRoute
  '/para/$id': typeof ParaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/intro': typeof IntroRoute
  '/paras': typeof ParasRoute
  '/settings': typeof SettingsRoute
  '/para/$id': typeof ParaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/intro': typeof IntroRoute
  '/paras': typeof ParasRoute
  '/settings': typeof SettingsRoute
  '/para/$id': typeof ParaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/complete' | '/intro' | '/paras' | '/settings' | '/para/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/complete' | '/intro' | '/paras' | '/settings' | '/para/$id'
  id:
    | '__root__'
    | '/'
    | '/complete'
    | '/intro'
    | '/paras'
    | '/settings'
    | '/para/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompleteRoute: typeof CompleteRoute
  IntroRoute: typeof IntroRoute
  ParasRoute: typeof ParasRoute
  SettingsRoute: typeof SettingsRoute
  ParaIdRoute: typeof ParaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paras': {
      id: '/paras'
      path: '/paras'
      fullPath: '/paras'
      preLoaderRoute: typeof ParasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para/$id': {
      id: '/para/$id'
      path: '/para/$id'
      fullPath: '/para/$id'
      preLoaderRoute: typeof ParaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompleteRoute: CompleteRoute,
  IntroRoute: IntroRoute,
  ParasRoute: ParasRoute,
  SettingsRoute: SettingsRoute,
  ParaIdRoute: ParaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
